spring.application.name=rrhh-usuarios
server.servlet.context-path=/rrhh
server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:rrhh
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:false}
spring.h2.console.path=/console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:*}
